### ISSUE TITLE
新版本页面管理器在页面退出动画不连续

### ISSUE THREAD

**Issue by zhbi98** [FASTSHIFT/X-TRACK#100]
![20231201195851](https://github.com/FASTSHIFT/X-TRACK/assets/49710448/cf102e92-b83f-4847-b4bb-b21cf7e6991b)

![20231201200306](https://github.com/FASTSHIFT/X-TRACK/assets/49710448/f8492f87-0ea5-4a0b-9eaf-ee61cb8757bd)

**Comment by FASTSHIFT** [comment]
`onViewDidDisappear`表示页面已经消失了，直接隐藏有什么问题呢，是因为动画最后一帧没有刷到屏幕上吗？可以给出对比视频。

**Comment by zhbi98** [comment]
以下是我的测试，测试设备并不是 X-TRACK，而是移植了 X-TRACK 页面管理器的设备，第1张onViewDidDisappear是没有执行隐藏的，第2张是在onViewDidDisappear 执行隐藏的效果
https://github.com/FASTSHIFT/X-TRACK/assets/49710448/cd52de1f-e5ca-4a8c-8574-72da983a92df
https://github.com/FASTSHIFT/X-TRACK/assets/49710448/c647ec26-60b6-421e-9f19-cfe9c246e905

**Comment by FASTSHIFT** [comment]
@zhbi98 
用的动画类型是`LOAD_ANIM_MOVE_BOTTOM`吗，我本地测了一下是正常的：

**Comment by zhbi98** [comment]
我用的动画是 LOAD_ANIM_MOVE_TOP

**Comment by FASTSHIFT** [comment]
`onViewDidDisappear`是在此页面动画结束后调用的，不会在`onViewWillDisappear`立即调用。

**Comment by zhbi98** [comment]
看到你的视频没有问题我感到好奇，所以想问一个我的疑问，为什么在上一个页面对象的 onViewWillDisappear 创建动画后，立即执行到上一个页面对象的 onViewDidDisappear 去隐藏上一个页面，在你这边不会导致上一个页面立即隐藏。因为动画需要一定时间，但是在递归的作用下 onViewWillDisappear ->onViewDidDisappear 是瞬间时间的事情。

**Comment by zhbi98** [comment]
> `onViewDidDisappear`是在此页面动画结束后调用的，不会在`onViewWillDisappear`执行后立即调用。

但是我似乎没有在动画结束函数看到调用 onViewDidDisappear 函数

**Comment by zhbi98** [comment]
看到了，看到了
![20231206222214](https://github.com/FASTSHIFT/X-TRACK/assets/49710448/cda68d97-f3ad-4a32-8775-106342c573d4)
![20231206222253](https://github.com/FASTSHIFT/X-TRACK/assets/49710448/104263a1-3201-43c3-a504-23bd5ee52abb)

**Comment by FASTSHIFT** [comment]
LVGL版本是多少？有修改过页面切换动画相关参数吗？可以在模拟器上复现吗？

**Comment by zhbi98** [comment]
看见了，是我的改造出现问题了
![20231206222214](https://github.com/FASTSHIFT/X-TRACK/assets/49710448/108579dd-3070-4caa-870e-55a6d0da153b)
![20231206222253](https://github.com/FASTSHIFT/X-TRACK/assets/49710448/d7a9a73b-bd13-40e8-8b33-72555507aef3)

**Comment by zhbi98** [comment]
不错，是我对代码稍作了一些修改，在状态机中多加了 StateUpdate 函数递归

**Comment by FASTSHIFT** [comment]
> 不错，是我对代码稍作了一些修改，在状态机中多加了 StateUpdate 函数递归

OK，还有做哪些修改吗？

**Comment by zhbi98** [comment]
其他没有，由于看到状态机的返回值为 下一个状态，所以顺手加了一个

**Comment by zhbi98** [comment]
不好意思是我疏忽了，为此我还给你 pull request 了一个修改，现在我去关闭它

**Comment by FASTSHIFT** [comment]
> 不好意思是我疏忽了，为此我还给你 pull request 了一个修改，现在我去关闭它

没关系，发现问题欢迎讨论~

**Comment by zhbi98** [comment]
你的页面生命周期管理模块，和消息订阅框架太好用了，很感谢你的分享
