### ISSUE TITLE
这个页面管理框架会有内存泄漏的现象吗?

### ISSUE THREAD

**Issue by AresXiaoHui** [FASTSHIFT/X-TRACK#105]
我移植了这个框架,当我切换界面再返回时,内存消耗会增加大约不到100B,每一次切换再返回都是如此,请问有人遇到过吗?

**Comment by FASTSHIFT** [comment]
可以尝试用VS的VLD工具或者GCC的LeakSanitizer进行定位，看一下是框架泄露还是用户程序泄露。码表上还未发现泄露现象。

**Comment by AresXiaoHui** [comment]
> 可以尝试用VS的VLD工具或者GCC的LeakSanitizer进行定位，看一下是框架泄露还是用户程序泄露。码表上还未发现泄露现象。

谢谢指点!看来大概率是我自己的问题!
