### ISSUE TITLE
关于复刻问题

### ISSUE THREAD

**Issue by monkeywq** [FASTSHIFT/X-TRACK#107]
你好，首先非常感谢开源这么棒的项目，我近期复刻过程中遇到几个问题，万望解答：
1.手工焊接的磁场传感器LIS3MDL焊坏了，没有这个芯片可以测速吗？
2.主菜单选择开始，提示失败音，是因为没有插内存卡吗？

**Comment by FASTSHIFT** [comment]
> 1.手工焊接的磁场传感器LIS3MDL焊坏了，没有这个芯片可以测速吗？

速度信息来自GPS模块，所以不影响测速。

> 2.主菜单选择开始，提示失败音，是因为没有插内存卡吗？

因为没定位成功，无法开始轨迹记录。

**Comment by monkeywq** [comment]
ok,刚刚焊接了GPS模块，使用的是ATGM336H，从菜单看读取的数据全是0，要对GPS模块做一些设置吗

**Comment by FASTSHIFT** [comment]
见常见故障排查： https://github.com/FASTSHIFT/X-TRACK/tree/main/Hardware

**Comment by monkeywq** [comment]
感谢解答，关于GPS又查看了板子上的串口接收口Rx,发现此IO持续3.3V,如果不是软件配置上拉输入，是不是可以说明焊接问题？
另外请问 磁场传感器和加速度计作用是什么？
