### ISSUE TITLE
有机会更新sdfat支持exfat嘛？

### ISSUE THREAD

**Issue by magpte** [FASTSHIFT/X-TRACK#108]
菜鸟，stlink还没到，看到sdfat v2支持exfat了，有机会可以更新的嘛？
https://github.com/greiman/SdFat

**Comment by FASTSHIFT** [comment]
你可以试试，如果可以的话发一个PR~

**Comment by magpte** [comment]
等小弟估计很久了，真的就是业余中的业余，平时生活很忙

**Comment by FASTSHIFT** [comment]
没事，等有空了再搞也行

**Comment by magpte** [comment]
哈哈哈哈，gg，发现自己不是这块料，连最简单的tinygps的更新到1.1.1beta都不会，关了关了关了
