### ISSUE TITLE
bool PageBase::StashPop(void* ptr, uint32_t size)返回值错误

### ISSUE THREAD

**Issue by smalixing** [FASTSHIFT/X-TRACK#112]
![image](https://github.com/user-attachments/assets/6eefeabc-449c-4a45-b149-b1398f4018a4)

**Comment by FASTSHIFT** [comment]
感谢指出，已修复：https://github.com/FASTSHIFT/X-TRACK/commit/e394e50a9cc82307e17dac798bd8f6ec335d124f
