### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by 0422-fwj** [FASTSHIFT/X-TRACK#113]
void StartupView::Delete() 里没有显式释放ui.cont,，不会导致内存泄漏吗

**Comment by FASTSHIFT** [comment]
> void StartupView::Delete() 里没有显式释放ui.cont,，不会导致内存泄漏吗

`ui.cont`是挂在`root`节点上的，lvgl会在删除`root`节点的时候会自动销毁所有子对象（包括`ui.cont`）。
root删除处理代码位于：https://github.com/FASTSHIFT/X-TRACK/blob/main/Software/X-Track/USER/App/Utils/PageManager/PM_State.cpp#L228 在页面退出后会执行`StateUnloadExecute`
