### ISSUE TITLE
keil5 编译源码错误，请教

### ISSUE THREAD

**Issue by polyGithub** [FASTSHIFT/X-TRACK#12]
> 

..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Numbers/parseNumber.hpp(76): error:  #304: no instance of overloaded function "ArduinoJson6180_51::VariantData::setInteger" matches the argument list

..\Libraries\SdFat\src\SdFat.h(333): error:  #441: argument list for class template "SdFileSystem" is missing

**Comment by polyGithub** [comment]
*** Using Compiler 'V5.05 (build 41)', folder: 'C:\Keil_v5\ARM\ARMCC\Bin'
*** Warning: Using Microlib and C++ file(s) might cause the linker to fail !
  
Rebuild target 'X-Track'
compiling DP_GPS.cpp...
compiling DP_Clock.cpp...
compiling DataProc.cpp...
compiling DP_SportStatus.cpp...
compiling App.cpp...
compiling DP_Power.cpp...
compiling DP_IMU.cpp...
compiling DP_MusicPlayer.cpp...
compiling DP_MAG.cpp...
compiling DP_Storage.cpp...
compiling DP_SysConfig.cpp...
compiling DP_TzConv.cpp...
compiling main.cpp...
compiling DP_Recorder.cpp...
..\Libraries\SdFat\src\SdFat.h(333): error:  #441: argument list for class template "SdFileSystem" is missing
             SdFileSystem::begin();
..\USER\App\Common\DataProc\DP_Recorder.cpp: 0 warnings, 1 error
compiling StartUpModel.cpp...
compiling StartUpView.cpp...
compiling DP_TrackFilter.cpp...
compiling StartUp.cpp...
compiling AppFactory.cpp...
compiling StatusBar.cpp...
compiling Dialplate.cpp...
compiling DialplateModel.cpp...
compiling DialplateView.cpp...
compiling SystemInfosModel.cpp...
compiling LiveMapModel.cpp...
compiling LiveMap.cpp...
compiling LiveMapView.cpp...
compiling TemplateModel.cpp...
compiling Template.cpp...
compiling SystemInfosView.cpp...
compiling font_bahnschrift_13.c...
compiling ResourcePool.cpp...
compiling TemplateView.cpp...
compiling font_bahnschrift_17.c...
compiling font_bahnschrift_32.c...
compiling font_bahnschrift_65.c...
compiling SystemInfos.cpp...
..\Libraries\SdFat\src\SdFat.h(333): error:  #441: argument list for class template "SdFileSystem" is missing
             SdFileSystem::begin();
..\USER\App\Pages\SystemInfos\SystemInfos.cpp: 0 warnings, 1 error
compiling font_agencyb_36.c...
compiling img_src_alarm.c...
compiling img_src_gps_arrow.c...
compiling img_src_gps_pin.c...
compiling img_src_battery.c...
compiling img_src_locate.c...
compiling img_src_menu.c...
compiling img_src_satellite.c...
compiling img_src_origin_point.c...
compiling img_src_stop.c...
compiling img_src_trip.c...
compiling img_src_pause.c...
compiling img_src_battery_info.c...
compiling img_src_bicycle.c...
compiling img_src_start.c...
compiling img_src_compass.c...
compiling img_src_gyroscope.c...
compiling img_src_map_location.c...
compiling img_src_system_info.c...
compiling img_src_storage.c...
compiling img_src_time_info.c...
compiling img_src_sd_card.c...
compiling lv_label_anim_effect.cpp...
compiling MapConv.cpp...
compiling lv_obj_ext_func.cpp...
compiling lv_anim_timeline_wrapper.c...
compiling PM_Anim.cpp...
compiling PM_Drag.cpp...
compiling ResourceManager.cpp...
compiling PM_State.cpp...
compiling PingPongBuffer.c...
compiling PM_Router.cpp...
compiling PM_Base.cpp...
compiling GPS_Transform.c...
compiling GPX.cpp...
compiling DataCenter.cpp...
compiling Account.cpp...
compiling GPX_Parser.cpp...
compiling TonePlayer.cpp...
compiling DateStrings.cpp...
compiling TileSystem.cpp...
compiling TileConv.cpp...
compiling TrackLineFilter.cpp...
compiling TrackPointFilter.cpp...
compiling Time.cpp...
compiling HAL.cpp...
compiling HAL_Clock.cpp...
compiling HAL_GPS.cpp...
compiling DisplayFault.cpp...
..\Libraries\SdFat\src\SdFat.h(333): error:  #441: argument list for class template "SdFileSystem" is missing
             SdFileSystem::begin();
..\USER\Display\DisplayFault.cpp: 0 warnings, 1 error
compiling Display.cpp...
compiling HAL_Backlight.cpp...
compiling StorageService.cpp...
..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Numbers/parseNumber.hpp(76): error:  #304: no instance of overloaded function "ArduinoJson6180_51::VariantData::setInteger" matches the argument list
            argument types are: (ArduinoJson6180_51::Integer)
            object type is: ArduinoJson6180_51::VariantData
          result.setInteger(Integer(~mantissa + 1));
..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Numbers/parseNumber.hpp(80): error:  #304: no instance of overloaded function "ArduinoJson6180_51::VariantData::setInteger" matches the argument list
            argument types are: (ArduinoJson6180_51::UInt)
            object type is: ArduinoJson6180_51::VariantData
        result.setInteger(UInt(mantissa));
..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantCompare.hpp(164): error:  #70: incomplete type is not allowed
      Comparer<Integer> comparer(lhs);
          detected during:
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantData::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::Comparer<ArduinoJson6180_51::VariantConstRef, void>]" at line 16 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantFunctions.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::variantAccept(const ArduinoJson6180_51::VariantData *, TVisitor &) [with TVisitor=ArduinoJson6180_51::Comparer<ArduinoJson6180_51::VariantConstRef, void>]" at line 245 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantRef.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantConstRef::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::Comparer<ArduinoJson6180_51::VariantConstRef, void>]" at line 201
            instantiation of "ArduinoJson6180_51::CompareResult ArduinoJson6180_51::compare(const T1 &, const T2 &) [with T1=ArduinoJson6180_51::VariantConstRef, T2=ArduinoJson6180_51::VariantConstRef]" at line 205
..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantCompare.hpp(169): error:  #70: incomplete type is not allowed
      Comparer<UInt> comparer(lhs);
          detected during:
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantData::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::Comparer<ArduinoJson6180_51::VariantConstRef, void>]" at line 16 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantFunctions.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::variantAccept(const ArduinoJson6180_51::VariantData *, TVisitor &) [with TVisitor=ArduinoJson6180_51::Comparer<ArduinoJson6180_51::VariantConstRef, void>]" at line 245 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantRef.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantConstRef::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::Comparer<ArduinoJson6180_51::VariantConstRef, void>]" at line 201
            instantiation of "ArduinoJson6180_51::CompareResult ArduinoJson6180_51::compare(const T1 &, const T2 &) [with T1=ArduinoJson6180_51::VariantConstRef, T2=ArduinoJson6180_51::VariantConstRef]" at line 205
..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantCompare.hpp(61): error:  #304: no instance of overloaded function "ArduinoJson6180_51::arithmeticCompare" matches the argument list
            argument types are: (ArduinoJson6180_51::Integer, bool)
      return arithmeticCompare(lhs, rhs);
          detected during:
            instantiation of "ArduinoJson6180_51::CompareResult ArduinoJson6180_51::Comparer<T, ArduinoJson6180_51::enable_if<<expression>, void>::type>::visitSignedInteger(ArduinoJson6180_51::Integer) [with T=bool]" at line 60 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantData.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantData::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::Comparer<bool, void>]" at line 16 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantFunctions.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::variantAccept(const ArduinoJson6180_51::VariantData *, TVisitor &) [with TVisitor=ArduinoJson6180_51::Comparer<bool, void>]" at line 245 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantRef.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantConstRef::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::Comparer<bool, void>]" at line 186
            instantiation of "ArduinoJson6180_51::CompareResult ArduinoJson6180_51::Comparer<T, ArduinoJson6180_51::enable_if<ArduinoJson6180_51::IsVisitable<T>::value, void>::type>::accept(TComparer &) [with T=ArduinoJson6180_51::VariantConstRef, TComparer=ArduinoJson6180_51::Comparer<bool, void>]" at line 175
            instantiation of "ArduinoJson6180_51::CompareResult ArduinoJson6180_51::Comparer<T, ArduinoJson6180_51::enable_if<ArduinoJson6180_51::IsVisitable<T>::value, void>::type>::visitBoolean(bool) [with T=ArduinoJson6180_51::VariantConstRef]" at line 66 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantData.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantData::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::Comparer<ArduinoJson6180_51::VariantConstRef, void>]" at line 16 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantFunctions.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::variantAccept(const ArduinoJson6180_51::VariantData *, TVisitor &) [with TVisitor=ArduinoJson6180_51::Comparer<ArduinoJson6180_51::VariantConstRef, void>]" at line 245 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantRef.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantConstRef::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::Comparer<ArduinoJson6180_51::VariantConstRef, void>]" at line 201
            instantiation of "ArduinoJson6180_51::CompareResult ArduinoJson6180_51::compare(const T1 &, const T2 &) [with T1=ArduinoJson6180_51::VariantConstRef, T2=ArduinoJson6180_51::VariantConstRef]" at line 205
..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantCompare.hpp(65): error:  #304: no instance of overloaded function "ArduinoJson6180_51::arithmeticCompare" matches the argument list
            argument types are: (ArduinoJson6180_51::UInt, bool)
      return arithmeticCompare(lhs, rhs);
          detected during:
            instantiation of "ArduinoJson6180_51::CompareResult ArduinoJson6180_51::Comparer<T, ArduinoJson6180_51::enable_if<<expression>, void>::type>::visitUnsignedInteger(ArduinoJson6180_51::UInt) [with T=bool]" at line 63 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantData.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantData::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::Comparer<bool, void>]" at line 16 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantFunctions.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::variantAccept(const ArduinoJson6180_51::VariantData *, TVisitor &) [with TVisitor=ArduinoJson6180_51::Comparer<bool, void>]" at line 245 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantRef.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantConstRef::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::Comparer<bool, void>]" at line 186
            instantiation of "ArduinoJson6180_51::CompareResult ArduinoJson6180_51::Comparer<T, ArduinoJson6180_51::enable_if<ArduinoJson6180_51::IsVisitable<T>::value, void>::type>::accept(TComparer &) [with T=ArduinoJson6180_51::VariantConstRef, TComparer=ArduinoJson6180_51::Comparer<bool, void>]" at line 175
            instantiation of "ArduinoJson6180_51::CompareResult ArduinoJson6180_51::Comparer<T, ArduinoJson6180_51::enable_if<ArduinoJson6180_51::IsVisitable<T>::value, void>::type>::visitBoolean(bool) [with T=ArduinoJson6180_51::VariantConstRef]" at line 66 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantData.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantData::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::Comparer<ArduinoJson6180_51::VariantConstRef, void>]" at line 16 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantFunctions.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::variantAccept(const ArduinoJson6180_51::VariantData *, TVisitor &) [with TVisitor=ArduinoJson6180_51::Comparer<ArduinoJson6180_51::VariantConstRef, void>]" at line 245 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantRef.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantConstRef::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::Comparer<ArduinoJson6180_51::VariantConstRef, void>]" at line 201
            instantiation of "ArduinoJson6180_51::CompareResult ArduinoJson6180_51::compare(const T1 &, const T2 &) [with T1=ArduinoJson6180_51::VariantConstRef, T2=ArduinoJson6180_51::VariantConstRef]" at line 205
..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Numbers/convertNumber.hpp(97): error:  #304: no instance of overloaded function "ArduinoJson6180_51::canConvertNumber" matches the argument list
            argument types are: (unsigned long long)
    return canConvertNumber<TOut>(value) ? TOut(value) : 0;
          detected during:
            instantiation of "TOut ArduinoJson6180_51::convertNumber<TOut,TIn>(TIn) [with TOut=int, TIn=unsigned long long]" at line 24 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantImpl.hpp"
            instantiation of "T ArduinoJson6180_51::VariantData::asIntegral<T>() const [with T=int]" at line 53 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/ConverterImpl.hpp"
            instantiation of "T ArduinoJson6180_51::Converter<T, ArduinoJson6180_51::enable_if<<expression>, void>::type>::fromJson(ArduinoJson6180_51::VariantConstRef) [with T=int]" at line 107 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantRef.hpp"
            instantiation of "ArduinoJson6180_51::enable_if<<expression>, T>::type ArduinoJson6180_51::VariantRef::as<T>() const [with T=int]" at line 150 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantRef.hpp"
            instantiation of "ArduinoJson6180_51::VariantRef::operator T() const [with T=int]" at line 85 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Object/MemberProxy.hpp"
            instantiation of "ArduinoJson6180_51::MemberProxy<TObject, TStringRef>::operator T() const [with TObject=ArduinoJson6180_51::JsonDocument &, TStringRef=const char *, T=int]" at line 173 of "..\USER\App\Utils\StorageService\StorageService.cpp"
..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Numbers/convertNumber.hpp(97): error:  #304: no instance of overloaded function "ArduinoJson6180_51::canConvertNumber" matches the argument list
            argument types are: (signed long long)
    return canConvertNumber<TOut>(value) ? TOut(value) : 0;
          detected during:
            instantiation of "TOut ArduinoJson6180_51::convertNumber<TOut,TIn>(TIn) [with TOut=int, TIn=signed long long]" at line 26 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantImpl.hpp"
            instantiation of "T ArduinoJson6180_51::VariantData::asIntegral<T>() const [with T=int]" at line 53 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/ConverterImpl.hpp"
            instantiation of "T ArduinoJson6180_51::Converter<T, ArduinoJson6180_51::enable_if<<expression>, void>::type>::fromJson(ArduinoJson6180_51::VariantConstRef) [with T=int]" at line 107 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantRef.hpp"
            instantiation of "ArduinoJson6180_51::enable_if<<expression>, T>::type ArduinoJson6180_51::VariantRef::as<T>() const [with T=int]" at line 150 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantRef.hpp"
            instantiation of "ArduinoJson6180_51::VariantRef::operator T() const [with T=int]" at line 85 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Object/MemberProxy.hpp"
            instantiation of "ArduinoJson6180_51::MemberProxy<TObject, TStringRef>::operator T() const [with TObject=ArduinoJson6180_51::JsonDocument &, TStringRef=const char *, T=int]" at line 173 of "..\USER\App\Utils\StorageService\StorageService.cpp"
..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Json/JsonSerializer.hpp(77): error:  #304: no instance of overloaded function "ArduinoJson6180_51::TextFormatter<TWriter>::writeInteger [with TWriter=ArduinoJson6180_51::Writer<FileWrapper, void>]" matches the argument list
            argument types are: (ArduinoJson6180_51::Integer)
            object type is: ArduinoJson6180_51::TextFormatter<ArduinoJson6180_51::Writer<FileWrapper, void>>
      _formatter.writeInteger(value);
          detected during:
            instantiation of "std::size_t ArduinoJson6180_51::JsonSerializer<TWriter>::visitSignedInteger(ArduinoJson6180_51::Integer) [with TWriter=ArduinoJson6180_51::Writer<FileWrapper, void>]" at line 60 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantData.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantData::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::PrettyJsonSerializer<ArduinoJson6180_51::Writer<FileWrapper, void>>]" at line 16 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantFunctions.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::variantAccept(const ArduinoJson6180_51::VariantData *, TVisitor &) [with TVisitor=ArduinoJson6180_51::PrettyJsonSerializer<ArduinoJson6180_51::Writer<FileWrapper, void>>]" at line 245 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantRef.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantConstRef::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::PrettyJsonSerializer<ArduinoJson6180_51::Writer<FileWrapper, void>>]" at line 20 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Document/JsonDocument.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::JsonDocument::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::PrettyJsonSerializer<ArduinoJson6180_51::Writer<FileWrapper, void>>]" at line 15 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Serialization/serialize.hpp"
            instantiation of "std::size_t ArduinoJson6180_51::doSerialize<TSerializer,TSource,TWriter>(const TSource &, TWriter) [with TSerializer=ArduinoJson6180_51::PrettyJsonSerializer, TSource=ArduinoJson6180_51::StaticJsonDocument<512U>, TWriter=ArduinoJson6180_51::Writer<FileWrapper, void>]" at line 22 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Serialization/serialize.hpp"
            instantiation of "std::size_t ArduinoJson6180_51::serialize<TSerializer,TSource,TDestination>(const TSource &, TDestination &) [with TSerializer=ArduinoJson6180_51::PrettyJsonSerializer, TSource=ArduinoJson6180_51::StaticJsonDocument<512U>, TDestination=FileWrapper]" at line 75 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Json/PrettyJsonSerializer.hpp"
            instantiation of "std::size_t ArduinoJson6180_51::serializeJsonPretty(const TSource &, TDestination &) [with TSource=ArduinoJson6180_51::StaticJsonDocument<512U>, TDestination=FileWrapper]" at line 249 of "..\USER\App\Utils\StorageService\StorageService.cpp"
..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Json/JsonSerializer.hpp(82): error:  #304: no instance of overloaded function "ArduinoJson6180_51::TextFormatter<TWriter>::writeInteger [with TWriter=ArduinoJson6180_51::Writer<FileWrapper, void>]" matches the argument list
            argument types are: (ArduinoJson6180_51::UInt)
            object type is: ArduinoJson6180_51::TextFormatter<ArduinoJson6180_51::Writer<FileWrapper, void>>
      _formatter.writeInteger(value);
          detected during:
            instantiation of "std::size_t ArduinoJson6180_51::JsonSerializer<TWriter>::visitUnsignedInteger(ArduinoJson6180_51::UInt) [with TWriter=ArduinoJson6180_51::Writer<FileWrapper, void>]" at line 63 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantData.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantData::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::PrettyJsonSerializer<ArduinoJson6180_51::Writer<FileWrapper, void>>]" at line 16 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantFunctions.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::variantAccept(const ArduinoJson6180_51::VariantData *, TVisitor &) [with TVisitor=ArduinoJson6180_51::PrettyJsonSerializer<ArduinoJson6180_51::Writer<FileWrapper, void>>]" at line 245 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Variant/VariantRef.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::VariantConstRef::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::PrettyJsonSerializer<ArduinoJson6180_51::Writer<FileWrapper, void>>]" at line 20 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Document/JsonDocument.hpp"
            instantiation of "TVisitor::result_type ArduinoJson6180_51::JsonDocument::accept(TVisitor &) const [with TVisitor=ArduinoJson6180_51::PrettyJsonSerializer<ArduinoJson6180_51::Writer<FileWrapper, void>>]" at line 15 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Serialization/serialize.hpp"
            instantiation of "std::size_t ArduinoJson6180_51::doSerialize<TSerializer,TSource,TWriter>(const TSource &, TWriter) [with TSerializer=ArduinoJson6180_51::PrettyJsonSerializer, TSource=ArduinoJson6180_51::StaticJsonDocument<512U>, TWriter=ArduinoJson6180_51::Writer<FileWrapper, void>]" at line 22 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Serialization/serialize.hpp"
            instantiation of "std::size_t ArduinoJson6180_51::serialize<TSerializer,TSource,TDestination>(const TSource &, TDestination &) [with TSerializer=ArduinoJson6180_51::PrettyJsonSerializer, TSource=ArduinoJson6180_51::StaticJsonDocument<512U>, TDestination=FileWrapper]" at line 75 of "..\USER\App\Utils\ArduinoJson\src\ArduinoJson/Json/PrettyJsonSerializer.hpp"
            instantiation of "std::size_t ArduinoJson6180_51::serializeJsonPretty(const TSource &, TDestination &) [with TSource=ArduinoJson6180_51::StaticJsonDocument<512U>, TDestination=FileWrapper]" at line 249 of "..\USER\App\Utils\StorageService\StorageService.cpp"
..\USER\App\Utils\StorageService\StorageService.cpp: 0 warnings, 10 errors
compiling HAL_SD_CARD.cpp...
..\Libraries\SdFat\src\SdFat.h(333): error:  #441: argument list for class template "SdFileSystem" is missing
             SdFileSystem::begin();
..\USER\HAL\HAL_SD_CARD.cpp: 0 warnings, 1 error
compiling HAL_Buzz.cpp...
compiling HAL_IMU.cpp...
compiling HAL_I2C_Scan.cpp...
compiling HAL_MAG.cpp...
compiling lv_disp.c...
compiling lv_event.c...
compiling lv_group.c...
compiling HAL_Encoder.cpp...
compiling lv_indev_scroll.c...
compiling HAL_Power.cpp...
compiling lv_indev.c...
compiling lv_obj_class.c...
compiling HAL_Audio.cpp...
compiling lv_obj_draw.c...
compiling lv_obj.c...
compiling lv_obj_pos.c...
compiling lv_obj_style_gen.c...
compiling lv_obj_tree.c...
compiling lv_obj_scroll.c...
compiling lv_obj_style.c...
compiling lv_theme.c...
compiling lv_refr.c...
compiling lv_draw_arc.c...
compiling lv_draw_blend.c...
compiling lv_draw_img.c...
compiling lv_draw_label.c...
compiling lv_draw_triangle.c...
compiling lv_draw_line.c...
compiling lv_draw_mask.c...
compiling lv_img_cache.c...
compiling lv_img_buf.c...
compiling lv_img_decoder.c...
compiling lv_theme_basic.c...
compiling lv_draw_rect.c...
compiling lv_flex.c...
compiling lv_grid.c...
compiling lv_theme_default.c...
compiling lv_calendar.c...
compiling lv_calendar_header_dropdown.c...
compiling lv_calendar_header_arrow.c...
compiling lv_list.c...
compiling lv_keyboard.c...
compiling lv_led.c...
compiling lv_imgbtn.c...
compiling lv_msgbox.c...
compiling lv_spinner.c...
compiling lv_colorwheel.c...
compiling lv_spinbox.c...
compiling lv_tileview.c...
compiling lv_font.c...
compiling lv_tabview.c...
compiling lv_win.c...
compiling lv_font_fmt_txt.c...
compiling lv_font_dejavu_16_persian_hebrew.c...
compiling lv_extra.c...
compiling lv_font_montserrat_8.c...
compiling lv_font_montserrat_10.c...
compiling lv_font_loader.c...
compiling lv_font_montserrat_12.c...
compiling lv_font_montserrat_12_subpx.c...
compiling lv_font_montserrat_18.c...
compiling lv_font_montserrat_14.c...
compiling lv_font_montserrat_16.c...
compiling lv_font_montserrat_22.c...
compiling lv_font_montserrat_26.c...
compiling lv_font_montserrat_24.c...
compiling lv_font_montserrat_20.c...
compiling lv_font_montserrat_28.c...
compiling lv_font_montserrat_28_compressed.c...
compiling lv_font_montserrat_32.c...
compiling lv_font_montserrat_30.c...
compiling lv_font_montserrat_36.c...
compiling lv_font_montserrat_34.c...
compiling lv_font_montserrat_42.c...
compiling lv_font_montserrat_38.c...
compiling lv_font_montserrat_40.c...
compiling lv_font_montserrat_46.c...
compiling lv_font_montserrat_44.c...
compiling lv_font_montserrat_48.c...
compiling lv_anim_timeline.c...
compiling lv_hal_indev.c...
compiling lv_font_unscii_16.c...
compiling lv_anim.c...
compiling lv_font_unscii_8.c...
compiling lv_hal_disp.c...
compiling lv_font_simsun_16_cjk.c...
compiling lv_bidi.c...
compiling lv_async.c...
compiling lv_gc.c...
compiling lv_color.c...
compiling lv_ll.c...
compiling lv_area.c...
compiling lv_fs.c...
compiling lv_math.c...
compiling lv_log.c...
compiling lv_templ.c...
compiling lv_hal_tick.c...
compiling lv_style.c...
compiling lv_mem.c...
compiling lv_style_gen.c...
compiling lv_timer.c...
compiling lv_printf.c...
compiling lv_txt_ap.c...
compiling lv_utils.c...
compiling lv_tlsf.c...
compiling lv_txt.c...
compiling lv_btn.c...
compiling lv_arc.c...
compiling lv_bar.c...
compiling lv_checkbox.c...
compiling lv_btnmatrix.c...
compiling lv_canvas.c...
compiling lv_img.c...
compiling lv_objx_templ.c...
compiling lv_dropdown.c...
compiling lv_line.c...
compiling lv_label.c...
compiling lv_roller.c...
compiling lv_slider.c...
compiling lv_switch.c...
compiling lv_table.c...
compiling lv_textarea.c...
compiling lv_meter.c...
compiling lv_snapshot.c...
compiling lv_animimg.c...
compiling lv_span.c...
compiling lv_chart.c...
compiling LIS3MDL.cpp...
..\Libraries\LIS3MDL\LIS3MDL.cpp(55): error:  #19: extra text after expected end of number
              if (sa1 != sa1_low && testReg(LIS3MDL_SA1_HIGH_ADDRESS, WHO_AM_I) == LIS3MDL_WHO_ID)
..\Libraries\LIS3MDL\LIS3MDL.cpp(64): error:  #19: extra text after expected end of number
              else if (sa1 != sa1_high && testReg(LIS3MDL_SA1_LOW_ADDRESS, WHO_AM_I) == LIS3MDL_WHO_ID)
..\Libraries\LIS3MDL\LIS3MDL.cpp(86): error:  #19: extra text after expected end of number
          address = (sa1 == sa1_high) ? LIS3MDL_SA1_HIGH_ADDRESS : LIS3MDL_SA1_LOW_ADDRESS;
..\Libraries\LIS3MDL\LIS3MDL.cpp(86): error:  #19: extra text after expected end of number
          address = (sa1 == sa1_high) ? LIS3MDL_SA1_HIGH_ADDRESS : LIS3MDL_SA1_LOW_ADDRESS;
..\Libraries\LIS3MDL\LIS3MDL.cpp: 0 warnings, 4 errors
compiling Adafruit_ST7789.cpp...
compiling lv_fs_sdfat.cpp...
..\Libraries\SdFat\src\SdFat.h(333): error:  #441: argument list for class template "SdFileSystem" is missing
             SdFileSystem::begin();
..\USER\Display\lv_port\lv_fs_sdfat.cpp: 0 warnings, 1 error
compiling lv_port_disp.cpp...
compiling StackInfo.c...
compiling LSM6DSM.cpp...
compiling lv_port_indev.cpp...
compiling TinyGPS++.cpp...
compiling Adafruit_GFX.cpp...
compiling FmtNumber.cpp...
compiling ButtonEvent.cpp...
compiling FatFileSFN.cpp...
compiling FatFilePrint.cpp...
compiling FatFileLFN.cpp...
compiling FatVolume.cpp...
compiling FatFile.cpp...
compiling fstream.cpp...
compiling istream.cpp...
compiling cm_backtrace.c...
compiling dtostrf.c...
compiling itoa.c...
compiling ostream.cpp...
compiling MinimumSerial.cpp...
compiling SdSpiSTM32.cpp...
compiling SdSpiCardEX.cpp...
compiling SdSpiCard.cpp...
compiling StdioStream.cpp...
compiling Arduino.c...
compiling Print.cpp...
compiling WMath.cpp...
compiling WString.cpp...
compiling HardwareSerial.cpp...
compiling Tone.cpp...
compiling Stream.cpp...
compiling WireBase.cpp...
compiling Wire.cpp...
compiling SPI.cpp...
compiling adc.c...
compiling delay.c...
compiling extend_SRAM.c...
compiling rtc.c...
compiling gpio.c...
compiling exti.c...
compiling timer.c...
compiling pwm.c...
compiling at32f4xx_adc.c...
compiling at32f4xx_bkp.c...
compiling at32f4xx_exti.c...
compiling at32f4xx_pwr.c...
compiling at32f4xx_rtc.c...
compiling at32f4xx_dma.c...
compiling at32f4xx_gpio.c...
compiling at32f4xx_rcc.c...
compiling at32f4xx_flash.c...
compiling at32f4xx_spi.c...
assembling startup_at32f403acgu7.s...
compiling misc.c...
compiling at32f4xx_usart.c...
compiling system_at32f4xx.c...
compiling at32f4xx_tim.c...
".\Objects\X-Track.axf" - 19 Error(s), 0 Warning(s).
Target not created.
Build Time Elapsed:  00:01:13

**Comment by FASTSHIFT** [comment]
@polyGithub 
您的Keil的版本是？
务必使用Keil v5.25版本以上进行编译，旧编译器不一定能识别较新的C++语法

**Comment by polyGithub** [comment]
> @polyGithub
> 您的Keil的版本是？
> 务必使用Keil v5.25版本以上进行编译，旧编译器不一定能识别较新的C++语法

好的，我的版本刚好是5.24的  我安装一个新的版本试试 ths

**Comment by polyGithub** [comment]
使用keil 5.27版本 编译无问题
