### ISSUE TITLE
[PR/WIP] ANT+ and BLE support (With App/Cellphone)

### ISSUE THREAD

**Issue by arinport** [FASTSHIFT/X-TRACK#13]
- [ ] Test under nRF52
- [ ] Magene speed/RPM/Heart-rate/Speedplay powermeter
- [ ] iPhone/Xiaomi BLE  & app test
- [ ] Chip selection (nRF52832/nRF51422/etc)
- [ ] SPI protocol definition

(...to be defined)

![IMG_2226](https://user-images.githubusercontent.com/75887203/127299255-e80958c9-5357-4ea9-81e0-b1d541666f31.jpg)

**Comment by FASTSHIFT** [comment]
二代码表已支持BLE，使用 AT32F437 + NRF52832 方案。
