### ISSUE TITLE
建了一个微信群，方便大家技术交流和经验分享

### ISSUE THREAD

**Issue by wwzh2015** [FASTSHIFT/X-TRACK#15]
虚位以待，快来加入呀*_^
如果7天以后下面的二维码过期了，大家直接微信搜索”X-TRACK技术交流“加入。
![login](https://z3.ax1x.com/2021/08/01/WzVT1A.png)

**Comment by jabezGit** [comment]
不是作者群，想探讨技术的，不建议加这群

**Comment by wwzh2015** [comment]
> 不是作者群，想探讨技术的，不建议加这群
你是scooo?
这个群就是讨论技术和落地的，如果不喜欢你可以退出

**Comment by saltfishh** [comment]
微信貌似搜不到,方便留个二维码吗

**Comment by wwzh2015** [comment]
[](url)

> 微信貌似搜不到,方便留个二维码吗

![login](https://z3.ax1x.com/2021/08/22/fzO7Gj.jpg)

**Comment by wwzh2015** [comment]
[](url)

> 微信貌似搜不到,方便留个二维码吗

![login](https://z3.ax1x.com/2021/08/22/fzO7Gj.jpg)

**Comment by saltfishh** [comment]
已经加了，十分感谢。

wwzh ***@***.***> 于 2021年8月22日周日 11:34写道：

**Comment by TaXue-DuBa** [comment]
> 虚位以待，快来加入呀*_^ 如果7天以后下面的二维码过期了，大家直接微信搜索”X-TRACK技术交流“加入。 ![login](https://camo.githubusercontent.com/052bf43a4701d143a630befb01d3aa074c3f83241b783e88ebbb5162f1b2edc9/68747470733a2f2f7a332e617831782e636f6d2f323032312f30382f30312f577a565431412e706e67)

搜不到啊，，留个二维码吧。。
