### ISSUE TITLE
X-Track复位问题以及屏幕背光

### ISSUE THREAD

**Issue by LiangtaoZhong** [FASTSHIFT/X-TRACK#18]
X-Track只有在用keil DEBUG的时候才能复位，但是要点三次run才能复位成功，然后屏幕停在主界面数秒后缓慢熄灭。平时上电则不能复位成功。我朋友的也是这样，不是焊接问题。麻烦了

**Comment by FASTSHIFT** [comment]
请检查复位电路是否正确焊接，电容电阻有没有焊反

**Comment by LiangtaoZhong** [comment]
> 请检查复位电路是否正确焊接，电容电阻有没有焊反

复位电路没有问题

**Comment by LiangtaoZhong** [comment]
屏幕背光解决了，是因为一个二极管焊反了，但是复位问题没有解决

**Comment by FASTSHIFT** [comment]
编码器可以正常交互吗，拨动和按压的时候都有操作音

**Comment by gyy0814** [comment]
是不是没焊电池啊   要焊上电池才行 usb并不能给芯片供电

**Comment by LiangtaoZhong** [comment]
谢谢，问题解决了，是因为boot0虚焊了。
