### ISSUE TITLE
有可行性的stm32方案吗

### ISSUE THREAD

**Issue by Wss-20170929** [FASTSHIFT/X-TRACK#25]
有可行性的stm32方案吗

**Comment by FASTSHIFT** [comment]
ST同封装且引脚兼容的，没有替代方案，因为主频、RAM、FLASH差距都很大。可以用STM32F405试试，但是得重新设计PCB。

**Comment by dotnfc** [comment]
[https://www.arterytek.com/download/ARTERY_AT32_MCU_Cross_Reference_Table_EN_V202011.xlsx](可以看看这个官方文档)

**Comment by FASTSHIFT** [comment]
@dotnfc 
AT32可以替代STM32，但是反过来不一定行，因为AT32的配置更高很多。

**Comment by dotnfc** [comment]
的确，AT32 性能高。如果真的考虑换 STM32 的话，我觉得 STM32G4Rx 应该可以。但是太贵，还不好买，现在。

**Comment by FASTSHIFT** [comment]
G4的RAM太小（最高128K）。当前程序FLASH占用260K，RAM占用200K。
