### ISSUE TITLE
地图文件的优化

### ISSUE THREAD

**Issue by dotnfc** [FASTSHIFT/X-TRACK#26]
用 1.6 的 java 地图下载器，下载地图后，再用 Tools\TilesConverterForLVGL.exe 工具进行转换，有两个问题：

- 这个工具可否改进一下，可指定输出目录，这样原图 .png 和 .bin 就可以分开，拷贝的时候，文件数量会少一半；
- 再一个，bin 文件一般是 256 * 256 * 2 = 128KB，有点浪费，特别是空图。是不是可以进行一个压缩处理？比如做一个 fs 的 filter。
我看 lv_lib_png 的 blog 说，'width x height x 4 byteRAM' 用 png/split-jpg 似乎 ram 不够。

**Comment by FASTSHIFT** [comment]
lv_lib_png需要完整的图片缓冲，在屏幕上显示需要多个tile拼接，目前RAM只有224K，所以无法支持PNG图片。
保留.png图片的原因是为了方便预览，如果不喜欢可以手动删除。
新一代的码表会优化硬件，支持直接解码png图片。

**Comment by dotnfc** [comment]
可否预告一下，大概思路？ 
'优化硬件' 是改 mcu 还是使用 st7789 的特性？

**Comment by FASTSHIFT** [comment]
@dotnfc 
AT32F435 + PSRAM

**Comment by dotnfc** [comment]
了解了。但是，官网没见着 AT32F435 呢？
既然换 mcu，为何不考虑一下 ESP32 呢？

**Comment by dotnfc** [comment]
真行。不知道什么时候能拿到样品。

**Comment by algoideas** [comment]
新一代支持png直接解码的什么时候发布
