### ISSUE TITLE
地图转换工具TilesConverterForLVGL.exe能否支持下ARGB8888

### ISSUE THREAD

**Issue by algoideas** [FASTSHIFT/X-TRACK#27]
地图转换工具TilesConverterForLVGL.exe能否可以支持下ARGB8888，目前已经在嵌入式Linux设备上移植成功，效果也正常，设备的Linux framebuffer驱动支持ARGB8888（不支持RGB565）

**Comment by FASTSHIFT** [comment]
可以分享视频吗？

**Comment by FASTSHIFT** [comment]
@algoideas 
 如果内存足够，可以考虑直接解码png图片进行显示，使用[lv_lib_png](https://github.com/lvgl/lv_lib_png)，省去转换过程。
