### ISSUE TITLE
关于其他品牌MCU替换的性能需求：主频>150M，RAM>=200K，FLASH>=512K，SPI速度>=50Mbps。  有没有推荐的型号。

### ISSUE THREAD

**Issue by Wss-20170929** [FASTSHIFT/X-TRACK#28]

**Comment by stig3** [comment]
stm32f405rgt6

**Comment by FASTSHIFT** [comment]
可以参考这个项目:
https://github.com/chenghongyao/X-TRACK

**Comment by Linjieqiang** [comment]
SWM32S 系列, 内置 8MB SDRAM, FLASH 512 KB, 应该可以满足?

**Comment by FASTSHIFT** [comment]
> SWM32S 系列, 内置 8MB SDRAM, FLASH 512 KB, 应该可以满足?

可以

**Comment by GetFreedomPro** [comment]
1.ESP32-S3 搭载 Xtensa 32 位 LX7 双核处理器
2.主频 240 MHz
3.512 KB SRAM
4.8 位 ~16 位并行 RGB,I8080, MOTO6800）, 支持 RGB565
5.支持片外 8M PSRAM
