### ISSUE TITLE
远程定位

### ISSUE THREAD

**Issue by mr-BY** [FASTSHIFT/X-TRACK#29]
希望可以支持远程查看位置和轨迹

**Comment by FASTSHIFT** [comment]
远程定位作用的是？防盗？

**Comment by mr-BY** [comment]
对，主要是可以查看当前位置

**Comment by mr-BY** [comment]
> 远程定位作用的是？防盗？

对，主要是可以查看当前位置

**Comment by FASTSHIFT** [comment]
要加防盗功能需要增加防拆设计，现阶段个人觉得研究这个意义不大。

**Comment by mr-BY** [comment]
> 要加防盗功能需要增加防拆设计，现阶段个人觉得研究这个意义不大。

可以在丢失后第一时间查看，或许有机会，至少比没有会好一些吧😄

**Comment by FASTSHIFT** [comment]
寻找也需要时间，而且在室内能可靠定位也是个问题。
就算是iPhone这种有防丢设计的，也不可能在短时间内找回来。
养成下车就拔码表的习惯，是最好的防丢手段。

**Comment by mr-BY** [comment]
好的，不过还是很期待后期可以加入
