### ISSUE TITLE
HAL部分代码和STM32F4的std_periph_driver不兼容啊

### ISSUE THREAD

**Issue by shawnchain** [FASTSHIFT/X-TRACK#32]
RT

**Comment by FASTSHIFT** [comment]
往什么芯片移植，怎么修改的，报什么错，请详细说明。

**Comment by shawnchain** [comment]
我想迁移到STM32F4，比对了Arduino-For-Keil项目里面的F4部分对应的Core/ArduinoAPI的代码，发现和这个项目中的代码有所出入。虽然这个版本KeilDuino版本是220，但是似乎代码逻辑更新一些。
请问有啥区别？
PS：我目前拿F429Discovery做开发板。

**Comment by FASTSHIFT** [comment]
涉及到Arduino API的代码没有太大区别。但是涉及标准库的部分要重新自己写。
