### ISSUE TITLE
可以详细介绍一下LVGL的UI界面设计吗，新手入门感觉难度比较大

### ISSUE THREAD

**Issue by gzyz9** [FASTSHIFT/X-TRACK#33]

**Comment by FASTSHIFT** [comment]
lvgl官方文档：
https://docs.lvgl.io/master/index.html

lvgl模拟器：
windows: https://github.com/lvgl/lv_sim_visual_studio
linux: https://github.com/lvgl/lv_sim_eclipse_sdl

**Comment by gzyz9** [comment]
已经下载了模拟器，也写过最简单那种汽车仪表盘界面，想学习一下这个项目的ui设计逻辑框架，不知道是否有相关介绍文档

**Comment by FASTSHIFT** [comment]
这个目前还没有写文档，设计时借鉴了MVP和iOS - ViewController的思路，可以结合代码的注释和[Template](https://github.com/FASTSHIFT/X-TRACK/tree/main/Software/X-Track/USER/App/Pages/_Template)学习一下。

**Comment by gzyz9** [comment]
![2021-09-18 16-46-38 的屏幕截图](https://user-images.githubusercontent.com/52118415/133883126-d709d6f5-90dd-4f8d-b821-0511e11412c9.png)
所有的ui相关都在这部分文件里面吗

**Comment by FASTSHIFT** [comment]
这个是模拟器，应用层代码在`USER/App`
