### ISSUE TITLE
想请教一些有关于时钟的问题

### ISSUE THREAD

**Issue by eternityqjl** [FASTSHIFT/X-TRACK#44]
您好，我在研究这个项目的DataProc的部分遇到一些疑问，想请教一下。系统上电初始化后Clock通过GPS (TzConv) 矫正RTC时钟，但矫正过程中DP_TzConv中首先更新了ArduinoTime库中的时间，然后使用ArduinoTime库中的时间返回给Clock。而之后的Recorder模块中直接通过Clock从RTC获取时间，那ArduinoTime库的时间还会在哪里用到呢？其他应用中为什么不直接使用RTC时间呢？

**Comment by FASTSHIFT** [comment]
ArduinoTime库主要是用来做时区转换，把UTC时间换算成北京时间，RTC校正后就不会被调用了。

**Comment by eternityqjl** [comment]
> 

嗯嗯明白了，感谢。

**Comment by eternityqjl** [comment]
还可以请教一下lvgl响应编码器按键和滚动的代码在哪里吗？我只看到在page中把组件加入了和input device相同的group，不太清楚lvgl是怎么调用page的onEvent的。

**Comment by FASTSHIFT** [comment]
input事件上通过group自动转发到控件上的。page的onEvent触发时，表示控件已经接收到事件了，用户只需关心如何响应事件就好了。
