### ISSUE TITLE
 V2.1开机黑屏问题

### ISSUE THREAD

**Issue by jppang** [FASTSHIFT/X-TRACK#49]
器件组合：

|GPS |IMU |MAG |开机|
|-----|------|------|-----|
|无     |   无     |  无      | 正常|
|无       | 有       |无       | 黑屏|
|有       | 无     | 无       |正常|
|有       | 有     |  无     |  黑屏|

另外使用V1.9版本的固件在上面的组合都开机正常。
请问各位有遇到相似的问题吗？

**Comment by FASTSHIFT** [comment]
重新拉份代码，这个加处理了。

**Comment by jppang** [comment]
更新新版固件后，已经可以正常开机了。
感谢。
