### ISSUE TITLE
switch 组件无法显示的问题？

### ISSUE THREAD

**Issue by bbear2** [FASTSHIFT/X-TRACK#57]
你好。
我在使用模拟器进行开发时需要用到[switch](https://docs.lvgl.io/master/examples.html#simple-switch)这个组件。经过初步调试，代码可以正常工作，点击后event事件能够正常响应。
但是在屏幕上没有显示对应的组件，我尝试调整过不通的背景颜色，均无法显示该控件。
想请问下需要做什么工作才能让switch组件正常显示？
感谢~

**Comment by bbear2** [comment]
> X-TRACK默认关闭了主题，所有控件默认样式都是透明的，可以尝试将`lv_conf.h`中的`LV_USE_THEME_DEFAULT`设置为1，重新启用默认样式。

刚刚测试了，可以正常显示了。
非常感谢~

**Comment by Neomaic** [comment]
我的vs模拟器出现9个连接错误，无法运行
