### ISSUE TITLE
结构与 PCB 形状如何完美耦合

### ISSUE THREAD

**Issue by zhbi98** [FASTSHIFT/X-TRACK#63]
大佬我想问个问题，就是我知道使用建模软件导出外壳 DXF 文件提供给 PCB 可以约定 PCB 板子的形状，我知道底面怎么做但是侧面怎么办？所以我的疑问是怎么通过导入结构设计文件的方式使得外壳侧边开口和 PCB 上接口位置对应起来。（比如外壳侧边 USB 开口和 PCB 板子上的 USB 接口契合）

**Comment by clz5100** [comment]
> 
AD导出STP文件，然后在建模软件里面设计就行了

**Comment by zhbi98** [comment]
> > 
> 谢谢你的回答
> AD导出STP文件，然后在建模软件里面设计就行了
