### ISSUE TITLE
关于GPS获取速度信息不准确的问题？

### ISSUE THREAD

**Issue by piaoxuebingfeng** [FASTSHIFT/X-TRACK#68]
大家有没有遇到过获取GPS的速度信息不准确的情况？我这边没有用作者推荐的GPS模块，而是买的别的家的模块，我手上有两块不同厂家的，获取的GPS速度信息都不太准确呢，有什么好的调整方式么？

**Comment by zhoushoujianwork** [comment]
硬件影响还是蛮大的，最好用推荐的或者更好的，省去定位不准的烦恼。
