### ISSUE TITLE
BOM  配单问题

### ISSUE THREAD

**Issue by Leo204-LKY** [FASTSHIFT/X-TRACK#7]
什么也不懂，没有经验，想拿这个项目练练手（是真的什么都不懂QwQ）    
拿去淘宝 BOM 配单的时候店家说这些不够详细  
大佬可以帮忙补充下吗，谢谢！  
  
FootPrint | Comment | LibRef | Designator | Quantity | 问题
-- | -- | -- | -- | -- | --
Pad_B | BAT_IN | Pad | BAT+ | 1 | 型号？
Pad_B | GND | Pad | BAT- | 1 | 型号？
蜂鸣器 | Buzzer | BZ | BZ1 | 1 | 体积  多少V  有源无源
_SMD5020 |   |   |   |   | 什么感值
电容_C0805 | 4.7UF | cap | C1,   C3 | 2 |  
电容_C0603 | 104 | cap | C2,   C4, C7, C8, C13, C18, C19, C20, | 12 |  
电容_C0603 | 106 | cap | C5 | 1 |  
电容_C1206 | 22uF | cap | C6 | 1 |  
电容_C0603 | 105 | cap | C9,   C10, C11, C12, C16, C17 | 6 |  
电容_C0603 | 22pf | cap | C14,   C15 | 2 |  
LED_0603 | red | LED | D1 | 1 |  
二极管_SOD-323 | 1N4148 | Diode | D2,   D3, D4, D5 | 4 |  
二极管_SOD-323 | 1N4007 | Diode | D6 | 1 |  
开关按键 | SKRP | SW-PB | K1 | 1 | 体积 直插还是贴片
HDR1X4H | Header   4 | Header   4 | P2 | 1 | 排针还是排母
接插件 | Micro_SD | Micro_SD | P3 | 1 | 发图确认
接插件 | MICRO   USB | MICRO   USB | P4 | 1 | 发图确认
MOS_SOT-23 | AO3401 | MOSFET-P | Q1 | 1 |  
MOS_SOT-23 | AON3400 | MOSFET-N | Q2 | 1 |  
MOS_SOT-23 | AO3400 | MOSFET-N | Q3,   Q4 | 2 |  
电阻_R0603 | 2K | Res | R1 | 1 |  
电阻_R0603 | 1K | Res | R2 | 1 |  
电阻_R0603 | 20K | Res | R3,   R4, R5, R6 | 4 |  
电阻_R0603 | 10K | Res | R7,   R8, R11, R13, R14, R15, R16 | 7 |  
电阻_R0603 | 100R | Res | R9,   R10 | 2 |  
电阻_R0603 | 10R | Res | R12 | 1 |  
SOT23-5 | MCP73831 | MCP73831 | U1 | 1 |  
SOT23-5 | LP5907-3.3 | LP5907 | U2 | 1 |  
AT主控 | AT32F403ACGU | AT32F403CGU6 | U3 | 1 |  
串口 | CH340E | CH340E | U4 | 1 |  
GPS-HTZN | HT1818Z3G5L | HT1818Z3G5L | U5 | 1 |  
LGA- | LIS3MDL | LIS3DMDL | U6 | 1 |  
LGA- | LSM6DSM | LSM6DSM | U7 | 1 |  
ZJY154T- | IPS154-12 | IPS154-12 | U8 | 1 | 完整型号
SIQ-02FVS3 | Rotary   Encoder | Rotary   Encoder | U9 | 1 |  
晶振_3215 | 32.768K | XTAL_A | Y1 | 1 |  
Total |  |  |  | 67 |  

Hardware 文件夹里的 BOM pdf 里因为 Footfrint 的不同内容之间没有横线分割所以可能把一项当成两项了，比如那个蜂鸣器…不过还是问一下具体的吧

**Comment by FASTSHIFT** [comment]
只能帮到你这里
https://github.com/FASTSHIFT/X-TRACK/blob/main/Hardware/README.md

**Comment by Leo204-LKY** [comment]
十分感谢！

**Comment by Leo204-LKY** [comment]
emmm碰到新问题了
AT32F403ACGU7这个芯片没货，有可以代替的吗

**Comment by FASTSHIFT** [comment]
@Leo204-LKY
可以换LQFP封装的AT32F403A，但是得会修改板子。

**Comment by Leo204-LKY** [comment]
> @Leo204-LKY
> 可以换LQFP封装的AT32F403A，但是得会修改板子。

AT32F403AVCT7可以吗？

**Comment by FASTSHIFT** [comment]
不行，FLASH容量至少512K，AT32F403AVCT7的FLASH大小是256KB。
另外，尽选小封装的MCU。

**Comment by Leo204-LKY** [comment]
> 不行，FLASH容量至少512K，AT32F403AVCT7的FLASH大小是256KB。
> 另外，尽选小封装的MCU。

![61190BCC-FF82-46E3-A1FB-59EE19368388](https://user-images.githubusercontent.com/57821066/126627824-f275fecf-26e4-427f-8839-6569f0022a08.jpeg)

在tb上找到一张这样的表，麻烦大佬看一下，哪些符合要求
改板子的事我可以找人
实在抱歉，问题比较多

**Comment by FASTSHIFT** [comment]
![image](https://user-images.githubusercontent.com/26767803/126632876-6c1da480-4ff2-4142-b6fc-1d91fe72abf1.png)
这个范围，体积要尽量小

**Comment by Leo204-LKY** [comment]
> ![image](https://user-images.githubusercontent.com/26767803/126632876-6c1da480-4ff2-4142-b6fc-1d91fe72abf1.png)
> 这个范围，体积要尽量小

好的，我去问问

**Comment by zhihancn** [comment]
大佬有计算下来这些成本大致要多少钱呢？

**Comment by FASTSHIFT** [comment]
@zhihancn 
大概不到300

**Comment by Leo204-LKY** [comment]
@zhihancn 嗯，差不多
但目前找不到 AT32F403A 芯片，建议要做的话先备好芯片

**Comment by zhihancn** [comment]
@FASTSHIFT
@Leo204-LKY  
哦哦哦，ok，谢谢大佬

**Comment by zxuewu** [comment]
请问电路板是需要自己焊接吗？（本人不懂电路设计。）如果是，能把你上面提到的完善好的BOM配单发出来吗，我也想搞一下。谢谢！

**Comment by Leo204-LKY** [comment]
> 请问电路板是需要自己焊接吗？（本人不懂电路设计。）如果是，能把你上面提到的完善好的BOM配单发出来吗，我也想搞一下。谢谢！

要自己焊接，不过tb也有加工的，不过价格就比较贵了
我最近没有时间做这个项目，所以只能暂时搁置了:/

**Comment by zinwalin** [comment]
> @zhihancn
> 大概不到300

现在应该是不太够了
