### ISSUE TITLE
关于页面管理器 页面状态 （PageState） 切换的问题

### ISSUE THREAD

**Issue by zilongmix** [FASTSHIFT/X-TRACK#72]
## 问题总结
在 `systeminfosView.cpp` 中存在函数 `onFocus` ,用于选项卡的切换。
![](https://cdn.jsdelivr.net/gh/zilongmix/doc/img/20220610113416.png)

我加入调试信息  `LV_LOG_USER("SYSTEMP-ONFOCUS\r\n");` 发现只有在每次键盘或鼠标输出时，才能进入到该函数中。而 `onFocus` 在如下函数中被调用。
![](https://cdn.jsdelivr.net/gh/zilongmix/doc/img/20220610113425.png)
查询代码最终在 `void PageManager::StateUpdate(PageBase* base)` 发现了页面状态切换的过程。
![](https://cdn.jsdelivr.net/gh/zilongmix/doc/img/20220610113929.png)

### 问题1：
![](https://cdn.jsdelivr.net/gh/zilongmix/doc/img/20220610114021.png)
在 `StateDidAppearExecute` 中返回的 **State** 为 `PAGE_STATE_ACTIVITY` ,按道理来说下次进入 `StateUpdate` 函数时，应该执行 `case PageBase::PAGE_STATE_ACTIVITY:` 分支，但调试发现，执行的一直是 `case PageBase::PAGE_STATE_DID_APPEAR:` 分支。
我想问问在哪里导致了状态的变化?

### 问题2：
![](https://cdn.jsdelivr.net/gh/zilongmix/doc/img/20220610120815.png)

为什么只有在鼠标键盘输出时，才会进入 `onViewDidAppear();` 函数，并打印我添加的信息。这个页面过程的具体代码在哪里？

**Comment by FASTSHIFT** [comment]
`onFocus()`在第一次页面进入显示完成时被`onViewDidAppear()`调用一次，是为了让`group`的第一个`obj`进入`focus`状态。后面的`onFocus()`都是在拨动鼠标滚轮的时候被`group`调用。

**Comment by zilongmix** [comment]
> `onFocus()`在第一次页面进入显示完成时被`onViewDidAppear()`调用一次，是为了让`group`的第一个`obj`进入`focus`状态并且移动到对应位置。后面的`onFocus()`都是在拨动鼠标滚轮的时候被`group`调用。
感谢！！

最终找到 `group` 回调函数如下：
![](https://cdn.jsdelivr.net/gh/zilongmix/doc/img/20220610130840.png)

**页面调度器理解**
`PageManager` 给用户提供的调度接口一共有三个
1. Pop
2. Push
3. BackHome
用户通过手动调用这三个接口，在不同页面之间切换。
页面 `Page` 的状态如下
```c
    /* Page state */
    typedef enum
    {
        PAGE_STATE_IDLE,
        PAGE_STATE_LOAD,
        PAGE_STATE_WILL_APPEAR,
        PAGE_STATE_DID_APPEAR,
        PAGE_STATE_ACTIVITY,
        PAGE_STATE_WILL_DISAPPEAR,
        PAGE_STATE_DID_DISAPPEAR,
        PAGE_STATE_UNLOAD,
        _PAGE_STATE_LAST
    } State_t;
```

不开启页面缓存下的切面调度流程如下图，所有页面都保存在一个 `页面栈` 中，栈顶为当前显示的页面。 
![](https://cdn.jsdelivr.net/gh/zilongmix/doc/img/20220610135240.png)
如果开启页面缓存，主要是少了 `PAGE_STATE_LOAD` 和 `PAGE_STATE_UNLOAD` 的两个状态，不用每次切换页面时，重新构造组件，但也增加了内存开销。
这样理解没错吧！

**Comment by FASTSHIFT** [comment]
> > `onFocus()`在第一次页面进入显示完成时被`onViewDidAppear()`调用一次，是为了让`group`的第一个`obj`进入`focus`状态并且移动到对应位置。后面的`onFocus()`都是在拨动鼠标滚轮的时候被`group`调用。
> > 感谢！！
> 
> 最终找到 `group` 回调函数如下： ![](https://camo.githubusercontent.com/390381925250f776cb0e17b12943bfb0b6f274618493b51191e28e723a67df92/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f7a696c6f6e676d69782f646f632f696d672f32303232303631303133303834302e706e67)
> 
> **页面调度器理解** `PageManager` 给用户提供的调度接口一共有三个
> 
> 1. Pop
> 2. Push
> 3. BackHome
>    用户通过手动调用这三个接口，在不同页面之间切换。
>    页面 `Page` 的状态如下
> 
> ```c
>     /* Page state */
>     typedef enum
>     {
>         PAGE_STATE_IDLE,
>         PAGE_STATE_LOAD,
>         PAGE_STATE_WILL_APPEAR,
>         PAGE_STATE_DID_APPEAR,
>         PAGE_STATE_ACTIVITY,
>         PAGE_STATE_WILL_DISAPPEAR,
>         PAGE_STATE_DID_DISAPPEAR,
>         PAGE_STATE_UNLOAD,
>         _PAGE_STATE_LAST
>     } State_t;
> ```
> 
> 不开启页面缓存下的切面调度流程如下图，所有页面都保存在一个 `页面栈` 中，栈顶为当前显示的页面。 ![](https://camo.githubusercontent.com/c3a76e56319f3738d83963deeb3f261a7438ac805e3eaa21ba38752ec761950d/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f7a696c6f6e676d69782f646f632f696d672f32303232303631303133353234302e706e67) 如果开启页面缓存，主要是少了 `PAGE_STATE_LOAD` 和 `PAGE_STATE_UNLOAD` 的两个状态，不用每次切换页面时，重新构造组件，但也增加了内存开销。 这样理解没错吧！

是的，页面缓存的意义是为了保持页面上下文信息，切回的时候可以保持原样而不是被重置。
