### ISSUE TITLE
编译linux源码生成xtrack后运行提示[DC][Error] Account[CENTER] was not found

### ISSUE THREAD

**Issue by xxzling** [FASTSHIFT/X-TRACK#74]
希望大佬解答，谢谢。

**Comment by FASTSHIFT** [comment]
程序提示了`input event device path`，需要加event设备的路径参数，例如`sudo ./xtrack /dev/input/event0`.

**Comment by xxzling** [comment]
感谢大佬回复，程序已经可以运行了，但显示似乎异常是和颜色深度有关吗，另外显示了以下日志
![image](https://user-images.githubusercontent.com/29038760/181303464-bdb3ccda-2f88-412d-86b1-c9de8a751ff9.png)
![image](https://user-images.githubusercontent.com/29038760/181303620-0a1a9a46-2d22-4375-8c10-90bc77abb0a7.png)

**Comment by FASTSHIFT** [comment]
修改`lv_conf.h`
```c
#define LV_COLOR_DEPTH 32
#define LV_COLOR_16_SWAP 0
```

**Comment by FASTSHIFT** [comment]
文件系统适配不是太完美，可能得摸索一下。

**Comment by xxzling** [comment]
感谢，已经成功在fb0设备上输出了
![image](https://user-images.githubusercontent.com/29038760/181305969-bc3c25b0-d9b2-4dbc-a379-f41e081aa13e.png)
