### ISSUE TITLE
码表底部的2个孔,如何与码表支架进行组合

### ISSUE THREAD

**Issue by yukiloh** [FASTSHIFT/X-TRACK#79]
看到作者的码表使用的是洛克兄弟的支架
![image](https://user-images.githubusercontent.com/54669645/194020131-7a88baa9-2656-4caf-b765-cb213c4d9b75.png)
请问连接支架与码表的部分是什么样子的,或者告知其商品名称

另,测量下来2个孔洞的参数如下,如果有误请指正
六角形内切圆半径: 2.7(毫米)
孔距: 21.128
小孔圆半径: 3
![image](https://user-images.githubusercontent.com/54669645/194020884-fba8714d-4e8a-4c58-b0ff-cc260c4e1a9d.png)

**Comment by FASTSHIFT** [comment]
参考[特殊器件购买链接](https://github.com/FASTSHIFT/X-TRACK/tree/main/Hardware#%E7%89%B9%E6%AE%8A%E5%99%A8%E4%BB%B6%E8%B4%AD%E4%B9%B0%E9%93%BE%E6%8E%A5)中的**码表底座**。
