### ISSUE TITLE
Add external folder to visual studio

### ISSUE THREAD

**Issue by obitvn** [FASTSHIFT/X-TRACK#80]
Sorry if this is not very relevant, but how can you add an external folder to visual studio, specifically here App and HAL folders.

**Comment by obitvn** [comment]
i tried to edit the config file of vs, but it can only add files that don't create folder like you and i can't build
![image](https://user-images.githubusercontent.com/43460353/197318458-028dd21d-f1a8-4f1a-bb2e-9717528f38a1.png)
My folder looks like this
![image](https://user-images.githubusercontent.com/43460353/197318483-28ad1695-b19e-4481-92a7-6e36d8897f6d.png)
It doesn't show up like your folder, I tried searching for solution many times on google but to no avail
![image](https://user-images.githubusercontent.com/43460353/197318535-0ad18e5b-f4f3-41c5-9a77-7af4d5be4603.png)

**Comment by FASTSHIFT** [comment]
Use the filter view instead of the folder view.

**Comment by obitvn** [comment]
thank you for the response, but it's not a view issue
![image](https://user-images.githubusercontent.com/43460353/197321994-93fcafd9-ba3d-400c-bbc1-f84b96feee1a.png)
i'm curious how did you add the external folder to the project? Add files one by one by dragging and dropping?

**Comment by obitvn** [comment]
after adding the files, it seems that visual studio can't find the .h files due to the path structure
![image](https://user-images.githubusercontent.com/43460353/197322196-42913948-313f-4d87-b301-10065ec42ec4.png)
![image](https://user-images.githubusercontent.com/43460353/197322199-57a0a355-f825-4323-a2da-725b59d81e61.png)
i guess this is because visual studio can't find this path in its root, i added it but vs still can't recognize it, how did you make visual studio work?
![image](https://user-images.githubusercontent.com/43460353/197322208-34fad3b9-608e-404c-bedf-3225a7ab04a2.png)

**Comment by obitvn** [comment]
After failed experiment with x-track i decided to create a new VS project myself and add the files i needed to it, it worked, simply copy folder, ctrl+v into VS, then exclude Unnecessary files, add the path to that folder at Property>C/C++>Additional Include Directory
![image](https://user-images.githubusercontent.com/43460353/197438771-68be3848-9de4-45fb-91aa-c88d5b77cbcf.png)
