### ISSUE TITLE
对于mvp模式的一个小问题

### ISSUE THREAD

**Issue by LNqueen** [FASTSHIFT/X-TRACK#85]
我移植这个框架有一个小问题，我理解的这个框架大概的流程就是数据和显示是分开的，当新数据到达时并不会直接交给界面去显示，而是将数据集中存放在一起（center），当view到达定时器设置的时间后开始更新界面的数据的信息，那如果我想使用一个弹窗来实时显示新到的数据，应该怎么做呢？如果按照mvp的思路走是不是只能等定时器计数完显示最新的数据呢？

**Comment by FASTSHIFT** [comment]
可以在Model层做一个回调到Presenter层，当收到数据更新事件时Persenter触发View更新

**Comment by LNqueen** [comment]
大概懂了，我等下试一下，感谢大佬😄
