### ISSUE TITLE
AT32F403ACGU7 是QFN封裝，可以焊接嗎，板子兼容嗎

### ISSUE THREAD

**Issue by jeremyvirtue** [FASTSHIFT/X-TRACK#86]
QFN封裝好像焊接難度會比較高

**Comment by greatws88** [comment]
可以啊  风枪一吹就搞定了。如果没有就用LQFP的封装改进版。https://github.com/FASTSHIFT/X-TRACK/tree/main/Hardware/X-TRACK%20改进版
