### ISSUE TITLE
请问作者如何实现测量剩余电量

### ISSUE THREAD

**Issue by yukiloh** [FASTSHIFT/X-TRACK#89]
看到状态管脚STAT直接接入MCU的31引脚,应该是为了显示充电动画
![image](https://user-images.githubusercontent.com/54669645/236149621-b9c024a2-4ea9-4649-906a-3fed33fe7e73.png)
![image](https://user-images.githubusercontent.com/54669645/236150112-a68f8d68-f5ba-42fa-9e05-1f3c2ca6c9c6.png)

而BAT_IN→VBAT直接接入MCU的供电引脚,也没有发现连接其他管脚进行电压测量
![image](https://user-images.githubusercontent.com/54669645/236150586-4fad66b7-21de-4b29-9ee9-62b9670592d0.png)

查阅代码看到有使用Hysteresis + MedianQueue,具体代码不太看得清,是通过软件算法实现电量计算的吗?

**Comment by FASTSHIFT** [comment]
PA1是接电量检测引脚，电量测量是直接通过电压换算的，然后过了一个滞回滤波和中值滤波。

**Comment by yukiloh** [comment]
> PA1是接电量检测引脚，电量测量是直接通过电压换算的，然后过了一个滞回滤波和中值滤波。

有用,不好意思看漏了分压电路...
