### ISSUE TITLE
低电压时电量电压显示不准确

### ISSUE THREAD

**Issue by Hoshigami007** [FASTSHIFT/X-TRACK#90]
当电压低于3.4+的时候只能显示3.4+，实际有可能低于3V，直到电池保护板保护都真不知道，保护之后由于充电默认开机，无法充电需要拆开用可调电源对电池预充电才能使用充电口充电

**Comment by FASTSHIFT** [comment]
文档里说了，去除D4二极管防止充电自动开机。
