### ISSUE TITLE
页面的自定义出场动画不起作用

### ISSUE THREAD

**Issue by LNqueen** [FASTSHIFT/X-TRACK#98]
我在使用页面管理框架的时候出现了这样的问题，我按照示例代码中的DialplateView文件中的动画时间线的方式创建了动画，大概是这样的
![image](https://github.com/FASTSHIFT/X-TRACK/assets/30171606/892eb6dc-0e2a-4b2a-8242-ffd7133866ab)
但是在设备上却好像没有效果，找了很久但是都没有找到原因，请问下这个大概可能是什么原因呢？
补充：
1.在开机动画之后我使用replace函数跳转到menu页面（我自己创建的页面），
![image](https://github.com/FASTSHIFT/X-TRACK/assets/30171606/b47e4a90-22dc-4bf5-9d00-0dbcc6b2b04c)
在vs模拟器中显示这个出场动画是起作用的，但是在实际的设备中这个动画是不起作用的；
2.在onCustomAttrConfig()，函数中我只写了则一行代码：SetCustomLoadAnimType(PageManager::LOAD_ANIM_NONE);
![image](https://github.com/FASTSHIFT/X-TRACK/assets/30171606/2dbe1900-2bf6-4eb1-a440-fcb9ac27d974)
3.我直接使用按钮来触发出场动画好像也不成功；
![image](https://github.com/FASTSHIFT/X-TRACK/assets/30171606/bed344cc-2399-4d4d-96ac-a2b41d1f2bc2)
4.lvgl的版本是8.3.9（一开始是8.1.0，后来为了解决这个问题升级到了8.3.9）
5.使用SetCustomLoadAnimType(PageManager::LOAD_ANIM_OVER_TOP)可以看到预设的页面出场动画；

额外：
我还出现了另外一个问题，那就是我是用push函数大概建立了一个三级的菜单页面（即从menu页面使用push函数跳转了两个页面），但是从第三个页面pop到第二个页面的时候画面就卡住了，但是程序是在运行的，不知道发生了什么~

我的问题可能有点多，如果大佬有空的话就抽空解答一下，非常感谢！！

**Comment by FASTSHIFT** [comment]
确认下模拟器的lv_conf.h和设备上的是不是一致的。
